export const STATE_FETCH = "STATE_FETCH";
export const STATE_FETCH_PENDING = "STATE_FETCH_PENDING";
export const STATE_FETCH_FULFILLED = "STATE_FETCH_FULFILLED";
export const STATE_FETCH_REJECTED = "STATE_FETCH_REJECTED";

export const GRADE_FETCH = "GRADE_FETCH";
export const GRADE_FETCH_PENDING = "GRADE_FETCH_PENDING";
export const GRADE_FETCH_FULFILLED = "GRADE_FETCH_FULFILLED";
export const GRADE_FETCH_REJECTED = "GRADE_FETCH_REJECTED";