export const STATE_FETCH = "STATE_FETCH";
export const STATE_FETCH_PENDING = "STATE_FETCH_PENDING";
export const STATE_FETCH_FULFILLED = "STATE_FETCH_FULFILLED";
export const STATE_FETCH_REJECTED = "STATE_FETCH_REJECTED";

export const GRADE_FETCH = "GRADE_FETCH";
export const GRADE_FETCH_PENDING = "GRADE_FETCH_PENDING";
export const GRADE_FETCH_FULFILLED = "GRADE_FETCH_FULFILLED";
export const GRADE_FETCH_REJECTED = "GRADE_FETCH_REJECTED";

export const CARDS_FETCH = "CARDS_FETCH";
export const CARDS_FETCH_PENDING = "CARDS_FETCH_PENDING";
export const CARDS_FETCH_FULFILLED = "CARDS_FETCH_FULFILLED";
export const CARDS_FETCH_REJECTED = "CARDS_FETCH_REJECTED";

export const DISTRICT_FETCH = "DISTRICT_FETCH";
export const DISTRICT_FETCH_PENDING = "DISTRICT_FETCH_PENDING";
export const DISTRICT_FETCH_FULFILLED = "DISTRICT_FETCH_FULFILLED";
export const DISTRICT_FETCH_REJECTED = "DISTRICT_FETCH_REJECTED";


export const GEOGRAPHY_FETCH = "GEOGRAPHY_FETCH";
export const GEOGRAPHY_FETCH_PENDING = "GEOGRAPHY_FETCH_PENDING";
export const GEOGRAPHY_FETCH_FULFILLED = "GEOGRAPHY_FETCH_FULFILLED";
export const GEOGRAPHY_FETCH_REJECTED = "GEOGRAPHY_FETCH_REJECTED";

export const IDENTITY_FETCH = "IDENTITY_FETCH";
export const IDENTITY_FETCH_PENDING = "IDENTITY_FETCH_PENDING";
export const IDENTITY_FETCH_FULFILLED = "IDENTITY_FETCH_FULFILLED";
export const IDENTITY_FETCH_REJECTED = "IDENTITY_FETCH_REJECTED";

export const CURRENT_DISTRICT_FETCH = "CURRENT_DISTRICT_FETCH";
export const CURRENT_DISTRICT_FETCH_PENDING = "CURRENT_DISTRICT_FETCH_PENDING";
export const CURRENT_DISTRICT_FETCH_FULFILLED = "CURRENT_DISTRICT_FETCH_FULFILLED";
export const CURRENT_DISTRICT_FETCH_REJECTED = "CURRENT_DISTRICT_FETCH_REJECTED";

export const CURRENT_STATE_FETCH = "CURRENT_STATE_FETCH";
export const CURRENT_STATE_FETCH_PENDING = "CURRENT_STATE_FETCH_PENDING";
export const CURRENT_STATE_FETCH_FULFILLED = "CURRENT_STATE_FETCH_FULFILLED";
export const CURRENT_STATE_FETCH_REJECTED = "CURRENT_STATE_FETCH_REJECTED";

export const SUBJECT_CARDS_FETCH = "SUBJECT_CARDS_FETCH";
export const SUBJECT_CARDS_FETCH_PENDING = "SUBJECT_CARDS_FETCH_PENDING";
export const SUBJECT_CARDS_FETCH_FULFILLED = "SUBJECT_CARDS_FETCH_FULFILLED";
export const SUBJECT_CARDS_FETCH_REJECTED = "SUBJECT_CARDS_FETCH_REJECTED";