export const STATE_FETCH = "STATE_FETCH";
export const STATE_FETCH_PENDING = "STATE_FETCH_PENDING";
export const STATE_FETCH_FULFILLED = "STATE_FETCH_FULFILLED";
export const STATE_FETCH_REJECTED = "STATE_FETCH_REJECTED";